### ISSUE TITLE
Difference from ECLint?

### ISSUE THREAD

**Issue by jednano** [ahmadnassri/echint#1]
Does this project do something that [ECLint](https://github.com/jedmao/eclint) doesn't? I'm not complaining, but definitely curious why this project was introduced a couple months after ECLint.

**Comment by ahmadnassri** [comment]
I did come across `ECLint` when I was initially researching, the difference for me is needing something simple and lightweight to simply check for the validity of files for the purpose of including in `pretest` step in projects as well as having configurations options in `package.json` and the Environment.

in that context `ECHint` is an utility on top of [`lintspaces`](https://github.com/schorfES/node-lintspaces) _which has been around as far back as Apr, 2014_

`ECLint` does a great job of diving deep into the `editorconfig` spec and providing the ability to infer and fix files, which is well beyond the scope of a "hinting" utility that `ECHint` strives to be :)

the `check` method in `ECLint` is also capable of achieving this, but it felt like a big overhead (given the project size) to include just for the purpose of checking ...

perhaps if `ECLint` can be broken down into multiple projects _(something like `eclint-core`, `eclint-check`, `eclint-fix`, `eclint-infer` etc ...)_ each with the shared lightweight core and diverse functionality, then joined with `eclint` as the all-in-one package, then that'll be awesome, and folks can choose to include relevant parts for different purposes.

in this context `eclint-check` would replace `echint`, maybe it can even inherit some of the functionality added (configuring through `package.json` + Environment) as the usage become wider.

**Comment by jednano** [comment]
I'm inclined to agree with you. If I could go back, I would definitely do that; however, I don't think I want to invest the time at this point. Thanks for your explanation! And great job on this package. It looks well done!

**Comment by ahmadnassri** [comment]
thanks! right back at ya! :+1:
