### ISSUE TITLE
echint doesn't run on Windows

### ISSUE THREAD

**Issue by theetrain** [ahmadnassri/echint#46]
I cannot tell for sure, but running `echint --verbose` on Linux yields errors just fine. Whereas on Windows I see nothing:

```
/path/to/repo>echint --verbose

/path/to/repo>
```

**Comment by ahmadnassri** [comment]
hmmm ... time to boot up some windows machines!

**Comment by dahlbyk** [comment]
FWIW, `echint` is working fine for me (with or without `--verbose`) on Windows with version 4.0.1.
