### ISSUE TITLE
Look for .editorconfig in more places

### ISSUE THREAD

**Issue by mcandre** [ahmadnassri/echint#59]
If no `.editorconfig` file is present in the current directory, look up the parent directories before giving up. A deeply nested project tree may have the `.editorconfig` file at the top-level, but desire to run echint in some of the leaf directories.

**Comment by ahmadnassri** [comment]
worth considering, performance would be my main concern, but perhaps `glob` can help there ... I'll add to my backlog, unless you wanna take a stab at it :)

**Comment by stefanmaric** [comment]
I think I can tackle this one. Will open a PR when I get the time.

**Comment by stefanmaric** [comment]
I was looking a bit into the code and I found out that implementing this behavior is a dead-simple one-line fix and works even better than expected.

Replacing [this line](https://github.com/ahmadnassri/echint/blob/master/lib/index.js#L41):

```javascript
 config: process.env.ECHINT_CONFIG || path.join(process.cwd(), '.editorconfig'),
```

...with:

```javascript
    config: process.env.ECHINT_CONFIG || '.editorconfig',
```

...will make it.

[lintspaces](https://github.com/schorfES/node-lintspaces) makes use of [editorconfig-core-js](https://github.com/editorconfig/editorconfig-core-js) which lookups `.editorconfig` files as defined in [editorconfig.org](http://editorconfig.org/#file-location):

> Where are these files stored?
> 
> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.
> 
> EditorConfig files are read top to bottom and the closest EditorConfig files are read last. Properties from matching EditorConfig sections are applied in the order they were read, so properties in closer files take precedence.

To test this out, I made a test folder, with some nested folders, with multiple copies of a `test.js` file that looks like this:

```javascript
let tabs = {
	x: 0
}

let spaces = {
  y: 0
} 
```

Line 2 is indented with tabs and line 6 is indented with spaces. And there's a trailing whitespace on line 7, to test the inheritance of .editorconfig rules.

The folder structure is the following:

```
├── .editorconfig
├── spacesDir
│   ├── .editorconfig
│   ├── overrideDir
│   │   ├── .editorconfig
│   │   └── test.js
│   └── test.js
├── tabsDir
│   ├── .editorconfig
│   ├── overrideDir
│   │   ├── .editorconfig
│   │   └── test.js
│   └── test.js
└── test.js
```

The `.editorconfig` file on the root:

```
root = true

[*]
trim_trailing_whitespace = true

[*.js]
indent_style = space
indent_size = 2
```

The `.editorconfig` file on the `spacesDir/` and `tabsDir/overrideDir/` folders:

```
[*.js]
indent_style = space
indent_size = 2
```

And the `.editorconfig` file on the `tabsDir/` and `/spacesDir/overrideDir/` folders:

```
[*.js]
indent_style = tab
indent_size = 2
```

So you get the idea, `test.js` files are exactly the same, and they will always be wrong for any of the `.editorconfig` files, just we want to know what rules are being caught up. And there are 3 diff `.editorconfig` configurations, the one on the root that wants soft tabs and no trailing spaces, two that want soft tabs and two that want hard tabs.

With the little tweak I mentioned, if you run `echint` on the root, you get:

```
Error: 5 file(s) did not pass EditorConfig validation
  spacesDir/overrideDir/test.js:6 Unexpected spaces found.
  spacesDir/overrideDir/test.js:7 Unexpected trailing spaces found.
  spacesDir/test.js:2 Unexpected tabs found.
  spacesDir/test.js:7 Unexpected trailing spaces found.
  tabsDir/overrideDir/test.js:2 Unexpected tabs found.
  tabsDir/overrideDir/test.js:7 Unexpected trailing spaces found.
  tabsDir/test.js:6 Unexpected spaces found.
  tabsDir/test.js:7 Unexpected trailing spaces found.
  test.js:2 Unexpected tabs found.
  test.js:7 Unexpected trailing spaces found.
```

Notice how rules are merged and applied successfully. Also if, for example, you run `echint` inside `spacesDir/`, you get:

```
Error: 2 file(s) did not pass EditorConfig validation
  overrideDir/test.js:6 Unexpected spaces found.
  overrideDir/test.js:7 Unexpected trailing spaces found.
  test.js:2 Unexpected tabs found.
  test.js:7 Unexpected trailing spaces found.
```

Confirming that the top root `.editorconfig` file is being loaded properly if we let `lintspaces` handle it.

I will open a PR in a sec.

**Comment by stefanmaric** [comment]
And here the code I used to test it in case someone wants to confirm:

[ecTest.zip](https://github.com/ahmadnassri/echint/files/738835/ecTest.zip)
