### ISSUE TITLE
passing files to check in command line is broken

### ISSUE THREAD

**Issue by RafLeszczynski** [ahmadnassri/echint#75]
Running echint in command line with selected files is broken.

for example:
```
node_modules/.bin/echint file-name.js
```

From what I find out by quick grep it is because for:
https://github.com/ahmadnassri/echint/blob/master/lib/bin.js#L28 - pass the whole `cmd` object to the function call.
Then inside `index.js` these files are never taken out from `cmd.args`. 
Finally this condition is true https://github.com/ahmadnassri/echint/blob/master/lib/index.js#L33 and `files` are being set to `undefined` and later global patten is applied: https://github.com/ahmadnassri/echint/blob/master/lib/index.js#L102

It looks like because of the way that arguments are passed from command line to the `echint` it's possible that also other options are broken. 

I'm happy to fix the file issue but the changes could break the other way of using `echint` - form code level. Could you please provide some context what I should look at / remember about not to break stuff.

**Comment by stefanmaric** [comment]
Hi @RafLeszczynski ,

There's a PR in place to fix it: #69 

It will hopefully be merged soon.
