### ISSUE TITLE
Relax "extends" module naming conventions

### ISSUE THREAD

**Issue by RafLeszczynski** [ahmadnassri/echint#76]
Currently the module name for sharable config needs to have strict pattern `echint-config-[name]`. Is it possible to make this rules more relaxed. For example the module i'd like to use is `editor-config-[company-name]`. With current setup it's impossible. I'm happy to submit the PR but before doing this I'd like to agree on how we want to handle the old and new extends functionality not to introduce regressions.

**Comment by jonathantneal** [comment]
@RafLeszczynski, I believe the pattern is strict to avoid multiple lookups, so that something like `react` looks for `echint-config-react` and doesn’t actually match `react` itself. Could you tell me what is the experience is like with babel, eslint, or stylelint?

**Comment by stefanmaric** [comment]
I would also mention that making it strictly `echint-config-[name]` makes for better discoverability: https://www.npmjs.com/search?q=echint-config-

**Comment by RafLeszczynski** [comment]
@jonathantneal @stefanmaric what about private npm registery and npm scopes. For example the shareable config could be `@org-name/editor-config`. This is my case

**Comment by iamnewton** [comment]
The convention here doesn't allow for anyone to use this with scopes; Both ESLint and Stylelint allow for scopes within their package.  However, ESLint does it the best by allowing you to just put the scope under the extends and it finds the package in `@scope/eslint-config`.  So in this case it would be `@scope/echint-config`
